/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include "time.h"
#include "stdlib.h"

char **
add_1_svc(char **argp, struct svc_req *rqstp)
{
	static char *result;
	time_t t = time(NULL);
	struct tm tm = *localtime(&t);

printf("now: %d-%d-%d %d:%d:%d\n", tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday, tm.tm_hour, tm.tm_min, tm.tm_sec);


	

//printf("hola %s\n", *argp);	
	FILE *datos = fopen("*dato.txt", "a+");

		if (datos == NULL){

			printf("No hay nada. \n");
			
		}
		else 
			
			
			fprintf(datos, "%s %d-%d-%d %d:%d:%d\n", *argp, tm.tm_year + 1900, tm.tm_mon + 1, 				tm.tm_mday, tm.tm_hour, tm.tm_min, tm.tm_sec);
			printf("Se agregó el nombre correctamente. \n");
			result = *argp;
			fclose(datos);
			return (&result);
			
		
}

char **
search_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;
       char *archivo;
       int contador = 0; 

printf("Server is searching for: %s\n",*argp); 
FILE *file= fopen("*dato.txt","r"); 
       if(file == NULL) {
       printf("No hay datos en el archivo\n");
       exit(1);
}
       char *s;
               
       const size_t line_size = 300;
       char* line = malloc(line_size);
       while (fgets(line, line_size, file) != NULL) 
       {
               s = strstr(line,*argp);
               if(s!=NULL){ 
                       contador++;
			printf("%s", line);
               }
       }
asprintf(&result,"Se encontró %s %i veces. \n", *argp, contador); 

printf("Server found in txt file %s %i times", *argp, contador); 
       return &result; 

}







































